SEED: 25
DATA:
  TEST_TO_VAL_RATIO: 0.2
ARCHITECTURE:
  DIM: 512
# Adam optimizer with learning rate $lr = 10^{-3"$, momentum parameters $\beta_{1} = 0.9, \beta_{2} = 0.999$ and regularization parameter \epsilon = 10^{-7}$."
ADAM:
  # LR: 0.005 # For batch size 256
  LR: 0.016
  BETA1: 0.9
  BETA2: 0.999
  EPS: 0.0000001
TRAIN:
  N_EPOCHS: 32
